name: Pull Request

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs: 
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npm run build
  
      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
